### ISSUE TITLE
Automatic opponent

### ISSUE THREAD

**Issue by deedos** [OMerkel/Oware#1]
Hi.

Is it possible to configure the game with the oponent being a robot ?
thanks

**Comment by OMerkel** [comment]
Sure this is possible...

Making up my mind on strength or level of AI now. I have been looking for other Oware / Ouril playing AIs lately. It seems like other implementations are playing Oware/Awari only. It's rare to find any Ouril rules (like being popular in some areas in Portugal or Portuguese countries). The strength of other implementations are quite restricted and therefore it is easy to win against these AIs (my personal point of view). A really strong program has been available called the "Awari Oracle" from some guys affiliated towards an university in the Netherlands (Maastricht or Amsterdam?). But unfortunately the Awari Oracle seems to be shut down. I cannot find it with any free access any longer. On the other hand the Awari Oracle claimed to have a perfect play. A full solution for a fixed rule set has been computed and has been stored in a database. Which is basically not an AI anymore. But still it was fascinating but not flexible regarding the rules. And there is really a huge variety of rule variants available as you might know... But they claimed to have Oware "solved" this way, well...

So I would like to implement both: Oware and Ouril. It shall be an AI player (not a pre-rendered database lookup of moves claimed to be perfect). I am not interested to have an AI with just beginners level. I might only implement one algorithm with some restrictions like a maximum number of traversed nodes and a maximum thinking time. Due to the fact I would like to run it on mobile devices I would like to avoid battery drains due to high CPU load. Meaning I would like to avoid any pondering (use of opponent's time in the background to render next moves).

There is a big number of Mini-Max / Alpha-Beta / Negamax / Negascout implementations out there which seem to be more or less weak players as stated above already. I might go for a Monte-Carlo based player instead and see if this is successful or not.

Any more comments related towards the thoughts already shared in this thread? Is it covering what you had in mind?

**Comment by OMerkel** [comment]
I plan to implement an AI player now.

It shall...
- play both - Oware and Ouril,
- play on moderate to strong level,
- offer to play any side of the game, 
- not do a look up with perfect play on a pre-rendered database,
- use a Monte-Carlo algorithm to actively suggest a move (There is a big number of Mini-Max / Alpha-Beta / Negamax / Negascout implementations out there which seem to be more or less weak players).
- work with some restrictions like a maximum number of traversed nodes and a maximum thinking time.
- avoid battery drains due to high continuous and parallel CPU load on mobile devices.
- avoid stuff like any pondering (use of opponent's time in the background to render next moves) or similar.

Any more comments related towards the thoughts already shared in this thread? Is it covering what you had in mind?
